# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: dist
  SHOPWARE_ENDPOINT: ${{ github.ref == 'refs/heads/main' && 'https://s23511.creoline.cloud' || 'https://s23511.creoline.cloud/webdev-staging' }}
  SHOPWARE_ACCESSTOKEN: ${{ github.ref == 'refs/heads/main' && 'SWSCRZFKNNVIMJUZV2FIRFDTTG' || 'SWSCMFDMY0THA1NNZGR3CTDSEQ' }}

jobs:
# Please do not rename this job
  build-project:
    name: build webdev-storefront-aurio
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Set Environment Variables
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
              echo "Setting environment variables for the main branch..."
              export shopwareEndpoint="https://s23511.creoline.cloud"
            elif [[ "$GITHUB_REF" == "refs/heads/stage" ]]; then
              echo "Setting environment variables for the stage branch..."
              export shopwareEndpoint="https://s23511.creoline.cloud/stage"
            else
              echo "Using default environment variables..."
              export SITE_URL="https://default-site-url.com"
              export shopwareEndpoint="https://s23511.creoline.cloud/stage"
            fi
         
            shopwareEndpoint: 'https://s23511.creoline.cloud/webdev-staging'
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}

      - name: Build Node assets
        run: |
          npm install --global yarn
          npx @shopware-pwa/cli init --ci --username=finn.stolle --password=capella2023!
          yarn build
          yarn generate

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 51d882b3-1401-46f4-9e75-8ae3a18488c1
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/webdev-storefront-aurio/config.yaml
          action: upload
